spring:
  jap:
    hibernate:
  #      ddl-auto: create-drop
  datasource:
    url: "jdbc:mysql://eyw6324oty5fsovx.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/p91ljnlc67whotic"
    username: gl2c3r2fna13se4w
    password: t2b2vpdgb3gxp5ss
    hikari:
      maxLifetime: 20000

server:
  port: ${port:8080}